server:
  port: 9003
spring:
  datasource:
    name: db1
    url: jdbc:mysql://localhost:3306/db1?useUnicode=true&characterEncoding=UTF8&&serverTimezone=GMT%2B8
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
  application:
    name: order9003
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.5.210:8848

mybatis:
  type-aliases-package: com.bz
  mapper-locations: classpath:mapper/*Mapper.xml
  config-location: classpath:mybatis-config.xml