server:
  port: 9003
spring:
  datasource:
    name: db1
    url: jdbc:mysql://localhost:3306/db1?useUnicode=true&characterEncoding=UTF8&&serverTimezone=GMT%2B8
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
  application:
    name: order9003
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.5.210:8848
  #zipkin服务地址
  zipkin:
    base-url: http://192.168.5.210:9411
  sleuth:
    sampler:
      #设置slueth采样率，默认0.1
      #1.0全部采样
      probability: 1.0
mybatis:
  type-aliases-package: com.bz
  mapper-locations: classpath:mapper/*Mapper.xml
  config-location: classpath:mybatis-config.xml
