server:
  port: 9050

spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          #和服务注册发现结合，后续可以使用服务名来调用服务
          enabled: true
      routes:
        - id: route_simple
          uri: https://www.zouwencong.com
          predicates:
            - Path=/archive
    nacos:
      discovery:
        server-addr: 192.168.5.210