spring:
  profiles:
    active: param_route
  application:
    name: gateway9050
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.5.210:8848
    gateway:
      discovery:
        locator:
          #和服务注册发现结合，后续可以使用服务名来调用服务
          enabled: true

server:
  port: 9050
---


spring:
  profiles: method_route
  cloud:
    gateway:
      routes:
        - id: method_route
          uri: https://example.com
          predicates:
            - Method=GET

---

spring:
  profiles: param_route
  cloud:
    gateway:
      routes:
        - id: param_route
          uri: https://example.com
          predicates:
            #“.” 匹配任意字符
            - Query=red, gree.
            #需含有参数名为red，值匹配gree 格式，格式为正则
#            - Query=red, gree[a-z]{2}
---
spring:
  profiles: my_route
  cloud:
    gateway:
      routes:
        - id: my_route
          uri: https://www.hao123.com/
          #自定义filter
          predicates:
            - My=custom