server:
  port: 9060
spring:
  application:
    name: security9060
security:
  oauth2:
    client:
      #自定义oauth2的客户端id password
      client-id: security
      client-secret: security1234
      registered-redirect-uri: http://www.baidu.com
      #可选，表示自定义的scope
      scope: [all,abc,check]
      #允许进入自动授权
      auto-approve-scopes: true