server:
  port: 9010

spring:
  datasource:
    name: db1
    url: jdbc:mysql://localhost:3306/db1?useUnicode=true&characterEncoding=UTF8&&serverTimezone=GMT%2B8
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
  application:
    name: common


mybatis:
  type-aliases-package: com.bz
  mapper-locations: classpath:mapper/*Mapper.xml
  config-location: classpath:mybatis-config.xml