server:
  port: 9020

spring:
  datasource:
    name: boot2020
    url: jdbc:mysql://47.108.133.131:3306/db1?useUnicode=true&characterEncoding=UTF8&&serverTimezone=GMT%2B8
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
  application:
    name: tech-study


#mybatis:
#  type-aliases-package: com.bz
#  mapper-locations: classpath:mapper/*Mapper.xml
#  config-location: classpath:mybatis-config.xml